/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiConsultationCompanionRouteImport } from './routes/ai-consultation-companion'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as RecordsRouteImport } from './routes/records'
import { Route as RemindersRouteImport } from './routes/reminders'
import { Route as SymptomCheckerRouteImport } from './routes/symptom-checker'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiConsultationCompanionRoute = AiConsultationCompanionRouteImport.update({
  id: '/ai-consultation-companion',
  path: '/ai-consultation-companion',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsRoute = RecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersRoute = RemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const SymptomCheckerRoute = SymptomCheckerRouteImport.update({
  id: '/symptom-checker',
  path: '/symptom-checker',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-consultation-companion': typeof AiConsultationCompanionRoute
  '/auth': typeof AuthRoute
  '/records': typeof RecordsRoute
  '/reminders': typeof RemindersRoute
  '/symptom-checker': typeof SymptomCheckerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-consultation-companion': typeof AiConsultationCompanionRoute
  '/auth': typeof AuthRoute
  '/records': typeof RecordsRoute
  '/reminders': typeof RemindersRoute
  '/symptom-checker': typeof SymptomCheckerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-consultation-companion': typeof AiConsultationCompanionRoute
  '/auth': typeof AuthRoute
  '/records': typeof RecordsRoute
  '/reminders': typeof RemindersRoute
  '/symptom-checker': typeof SymptomCheckerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-consultation-companion'
    | '/auth'
    | '/records'
    | '/reminders'
    | '/symptom-checker'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-consultation-companion'
    | '/auth'
    | '/records'
    | '/reminders'
    | '/symptom-checker'
  id:
    | '__root__'
    | '/'
    | '/ai-consultation-companion'
    | '/auth'
    | '/records'
    | '/reminders'
    | '/symptom-checker'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiConsultationCompanionRoute: typeof AiConsultationCompanionRoute
  AuthRoute: typeof AuthRoute
  RecordsRoute: typeof RecordsRoute
  RemindersRoute: typeof RemindersRoute
  SymptomCheckerRoute: typeof SymptomCheckerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-consultation-companion': {
      id: '/ai-consultation-companion'
      path: '/ai-consultation-companion'
      fullPath: '/ai-consultation-companion'
      preLoaderRoute: typeof AiConsultationCompanionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records': {
      id: '/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof RecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders': {
      id: '/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof RemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/symptom-checker': {
      id: '/symptom-checker'
      path: '/symptom-checker'
      fullPath: '/symptom-checker'
      preLoaderRoute: typeof SymptomCheckerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiConsultationCompanionRoute: AiConsultationCompanionRoute,
  AuthRoute: AuthRoute,
  RecordsRoute: RecordsRoute,
  RemindersRoute: RemindersRoute,
  SymptomCheckerRoute: SymptomCheckerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
